import { SignJWT } from "jose";
import Database from "better-sqlite3";
const BASE = "https://didier-catering-production.up.railway.app";
const leer = () => new Promise((r) => { let s=""; process.stdin.on("data",d=>s+=d).on("end",()=>r(s)); });
const vars = JSON.parse(await leer());
console.log("AUTH_SECRET leida de Railway:", vars.AUTH_SECRET ? vars.AUTH_SECRET.length + " caracteres" : "NO VINO");
const db = new Database(process.env.SC + "/g4.db");
const u = db.prepare("select id,name,role,email from User where role='ADMIN' limit 1").get();
console.log("usuario admin de la copia:", u.name, u.email, u.id);
const tok = await new SignJWT({id:u.id,name:u.name,role:u.role,email:u.email}).setProtectedHeader({alg:"HS256"}).setIssuedAt().setExpirationTime("30m").sign(new TextEncoder().encode(vars.AUTH_SECRET));
const r = await fetch(BASE + "/", { headers: { Cookie: "didier_session=" + tok }, redirect: "manual" });
console.log("GET / con la sesion:", r.status, r.headers.get("location") ?? "");
const api = await fetch(BASE + "/api/notifications/count", { headers: { Cookie: "didier_session=" + tok } });
console.log("la API contesta:", api.status, (await api.text()).slice(0, 120));
